# Generated by Django 3.2.6 on 2021-11-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantilla',
            name='archivo',
            field=models.FileField(upload_to='plantillas'),
        ),
    ]
