# Generated by Django 4.0 on 2021-12-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0003_alter_certificado_codigo_verificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario_curso',
            name='estado',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='usuario_curso',
            name='fecha_completado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario_curso',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
