# Generated by Django 4.0 on 2021-12-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificados', '0004_alter_usuario_curso_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_id',
            field=models.CharField(choices=[('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extranjería'), ('TI', 'Tarjeta de identidad '), ('NIT', 'NIT')], default='CC', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='certificado',
            constraint=models.UniqueConstraint(fields=('usuario', 'curso'), name='unico certificado'),
        ),
        migrations.AddConstraint(
            model_name='usuario_curso',
            constraint=models.UniqueConstraint(fields=('usuario', 'curso'), name='unico usuario_curso'),
        ),
    ]
